#!/usr/bin/env bash

# Function to display subdomain information
display_info() {
  local domain=$1
  local subdomain=$2

  if [[ -z $subdomain ]]; then
    # If subdomain parameter is not provided, display information for default subdomains
    subdomains=("www" "lb-01" "web-01" "web-02")
  else
    # If subdomain parameter is provided, display information for the specified subdomain
    subdomains=($subdomain)
  fi

  for sub in "${subdomains[@]}"; do
    record=$(dig +short $sub.$domain)
    record_type=$(dig +short $sub.$domain | awk '{print $4}')

    echo "The subdomain $sub is a $record_type record and points to $record"
  done
}

# Check the number of command-line arguments
if [[ $# -lt 1 || $# -gt 2 ]]; then
  echo "Usage: $0 <domain> [subdomain]"
  exit 1
fi

# Call the display_info function with the provided arguments
display_info "$@"
