#!/usr/bin/env bash
#Install nginx web server
#write a Bash script that configures a new Ubuntu machine
#+ to respect above requirements.

apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'

# Configure Nginx
echo "Hello World!" > /var/www/html/index.html

# Restart Nginx
service nginx restart
