#!/usr/bin/env bash
#Install nginx web server
#write a Bash script that configures a new Ubuntu machine
#+ to respect above requirements.

apt-get -y update
apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'

# Configure Nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Restart Nginx
service nginx restart
