#!/usr/bin/env bash
#Configure my  Nginx server so that /redirect_me is redirecting to another page.

# Install nginx and start it
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" >> /var/www/html/index.html
sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www

# Redirect to /redirect_me to a youtube video
sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

service nginx start
