#!/usr/bin/env bash
# Adjust Nginx configuration to listen on port 80

sudo rm /etc/nginx/sites-enabled/default
sudo sh -c "echo 'server { listen 80; server_name _; location / { } }' > /etc/nginx/sites-available/default" && sudo service nginx restart

#sed -i 's/listen\s*80;/listen 80;/' /etc/nginx/sites-available/default
