#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.

sudo sh -c "echo 'server { listen 80; server_name _; location / { } }' > /etc/nginx/sites-available/default" && sudo systemctl restart nginx
