#!/usr/bin/env bash
#a Bash script that:
#Creates the file "/var/run/myscript.pid" containing its PID
#Displays "To infinity and beyond" indefinitely
#Displays "I hate the kill command" when receiving a SIGTERM signal
#Displays "Y U no love me?!" when receiving a SIGINT signal
#Deletes the file "/var/run/myscript.pid" and terminates itself 
#when receiving a SIGQUIT or SIGTERM signal.

echo "$$" > /var/run/myscript.pid

terminator()
{
	rm /var/run/myscript.pid
	exit
}

for (( ; ; ))
do
	echo "To infinity and beyond"
	sleep 1
	trap 'echo "Y U no love me?!"' 2
	trap 'echo "I hate the kill command" && terminator' 15
	trap 'terminator' 3
done	
