#!/usr/bin/env bash
#a Bash script that displays the content of the file /etc/passwd
#the script should only display:
#username, user id,and Home directory path for the user 

while read -r passwd
do
	echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
