#!/usr/bin/env bash
#a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.
# Tells a story based on the contents of the `/etc/passwd` file.

IFS=':'
while read -r user pass uid gid username_f homedir loginshell
do
	echo "The user $user is part of the $gid gang,"\
	"lives in $homedir and rides $loginshell."\
	"$uid's place is protected by the passcode $pass,"\
	"more info about the user here: $username_f"
done </etc/passwd
