#!/usr/bin/env bash
# a Bash script that groups visitors by IP and HTTP status code, and displays this data.
#you’ve parsed the Apache log file

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
