#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080.

# Update nginx configuration
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf

# Change the default listen port to 8080
sed -i 's/listen 80/listen 8080/' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
# Start nginx service
sudo -u nginx service nginx start
